In [1]:
import numpy as np
import tensorflow as tf

In [2]:
scalar = tf.constant([2])
vector = tf.constant([5, 6,2])
matrix = tf.constant([[1, 2, 3], [2, 3, 4], [3, 4,5]])
tensor = tf.constant([[[1,2,3],[2, 3, 4], [3, 4, 5]], [[4,5,6],[5,6,7],[6,7,8]], [[7,8,9], [8,9,10],[9,10,11]] ])

In [3]:
with tf.Session() as sess:
    print ('Scalar is :', sess.run(scalar))
    print ('Vector is :', sess.run(vector))
    print ('Matrix is :', sess.run(matrix))
    print ('Tensor is :', sess.run(tensor))

Scalar is : [2]
Vector is : [5 6 2]
Matrix is : [[1 2 3]
 [2 3 4]
 [3 4 5]]
Tensor is : [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


## Variables

In [4]:
state = tf.Variable(0)
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

init_op = tf.initialize_all_variables()


In [5]:
with tf.Session() as sess:
    sess.run(init_op)
    print('State = ', sess.run(state))
    for _ in range(3):
        sess.run(update)
        print ('State = ', sess.run(state))

State =  0
State =  1
State =  2
State =  3


## Placeholders 

In [7]:
a = tf.placeholder(tf.float32)
b = a * 2
with tf.Session() as sess:
    result = sess.run(b, feed_dict={a: 3.5})
    print ('Result = ', result)
    
    
with tf.Session() as sess:
    result = sess.run(b, feed_dict={a: [1.0, 2.0, 3.5]})
    print ('Result = ', result)

Result =  7.0
Result =  [ 2.  4.  7.]
